#!/bin/bash

name=$2
if [ "$name" == "" ]; then
    name="Main"
fi

python3 compile.py "$1" "${name}.asm" --name "$name"

ret=$?
if [ $ret -eq 0 ]; then
    python3 assemble.py "${name}.asm" "OBJ/${name}.json"
fi
