#!/bin/bash

name=$2
if [ "$name" == "" ]; then
    name="Main"
fi

classes=`python3 compile.py "$1" "${name}.asm" --name "$name" --list`

ret=$?
if [ $ret -eq 0 ]; then
    for cls in $classes
    do
        python3 assemble.py "${cls}.asm" "OBJ/${cls}.json"
        ret=$?
        if [ $ret -ne 0 ]; then
            exit 1
        fi
    done
fi
